version: '3'
services:
  # Create kibana container 
  kibana:
    image: kibana:6.4.2
    container_name: kibanaserver
    restart: unless-stopped
    tty: true
    volumes:
      - kibana:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - kibana-network

  # Create nginx container 
  nginxserver:
    image: nginx:alpine
    container_name: nginxserver
    restart: unless-stopped
    tty: true
    volumes:
      - nginxserver/:/var/www
    ports:
      - "80:80"
      - "443:443"
    networks:
      - kibana-network

  # Create mysql container 
  mysqlserver:
    image: mysql:5.7.22
    container_name: mysqlserver
    restart: unless-stopped
    tty: true
    volumes:
      - mysqlserver:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
    networks:
      - kibana-network

#Docker Networks
#networks:
#  kibana-network:
#    driver: bridge